### PR TITLE
Should be good now!

### PR DESCRIPTION
**Pull request by nouse4anick**
Ok, new lesson: before commit check the module in IDLE first!

it runs now, I do recommend going through and cleaning out commented code that is no longer needed (which i'll do later when I have some more free time if you'd like).

73
Art
KC7SDA

### CODE REVIEW

**Comment by scotthibbs** [comment]
​Cleaning out the commented code is fine by me.

I also wish to move the functions and classes so that the main code is all
together - at least as much as we can. I did this before and it broke so I
reverted back. I've learned python just for this program so I'm still a
newbie.

Thanks for the work!!



Scott Hibbs

Computer Technology Services
I deliver technology fixes
812-581-0631

**Comment by scotthibbs** [comment]
​Hey,

Does the def proc_key(ch): need changed to accept upper and lower now?

Scott Hibbs

Computer Technology Services
I deliver technology fixes
812-581-0631

**Comment by scotthibbs** [comment]
I've completed another enhancement. The log section now relists the log
when an edit or delete has occurred. This will eliminate confusion over
what is left in the log after a delete/edit. When/if you start coding again
be sure to grab the new code.

Thanks,
Scott

Scott Hibbs

Computer Technology Services
I deliver technology fixes
812-581-0631

**Comment by nouse4anick** [comment]
I'm not sure yet if the proc_key(ch) needs to be changed, I've pulled the new code and I'm going to go over it this weekend a little bit (kinda busy with home improvement and conducting a wedding). I've told the club I'm in that we'll be using this for next FD because I'm sick of merging 2 logs by hand!

Also, I'll come up with some tests and create a directory/set of files full of tests that we can run to try to break FDlog and make sure it works the way we intend it.

**Comment by scotthibbs** [comment]
Art,

Sounds kewl.

I have to respond through github as I don't know if I have your email. Mine
is scotthibbs at gmail.com.

I have finished with my "up arrow" enhancement. (This FD, I kept hitting
enter instead of space after a call.) So now you can up arrow to get what
was last entered. So I did change the proc_key function a bit. I will
upload to github tonight after this email.

I will look into copy/paste functionality next (for those using other
programs and need to copy/paste).

Scott

**Pull request merged**
