### PR TITLE
field day 2019 update

### PR DESCRIPTION
**Pull request by nouse4anick**
- cleaned whitespace code (ie all revision history moved to readme file)
- fixed possible memory leak (updatebb() method .bind)

note this code also includes the winter field day update

### CODE REVIEW

**Review by scotthibbs — COMMENTED** [review]
Great Work!!

**Comment by nouse4anick** [comment]
thanks! I hope with the major memory leak fixed that it wont keep freezing on the pi.

one of the other things I would like to work on is trying to make this more modular, meaning that one can take a template file, add some stuff to it, and 'import' it to fdlog as an added contest (ie output, exchange that's recorded, etc). This will allow for other contests to be made (ie the NA qso party) to be added quickly and efficiently. 

I might also try my hand at turning the configuration into a gui interface instead of the cli, this would also help in making other contests available and to configure them relatively painlessly.

**Comment by scotthibbs** [comment]
Hey thanks Art,

The memory leak is all mine. That routine was created as one of the first
things that I wanted from the original FDLog. I think I took that binding
line from either the original author Alan Biocca, WB6ZQZ or some place
online. My confession is that I have no clue what a lambda e is anymore.
lol  I have been away from python for several years now.

Should we be working on porting it to python 3?

Talking about the original FDLog, I would like to keep credit in the
program mentioning that we have forked his work and most of the backbone is
his (Alan Biocca). I have just been enhancing it on my own since he
wouldn't commit any enhancements that I made. I am AGAINST using a hardware
clock that he employed for the time master. We don't need atomic clock time
synchronization! We just got to agree to on one time.

Might want to download the latest original fdlog to look at it, fdlog 154c.
(www.fdlog.info) It is flawed (betas) and I think he is behind us in
functionality. Ours is pretty. lol  For example he is having trouble duping
caps and lower case calls which we solved first thing by not allowing caps
there... He has added networking to allow it to connect through the
internet. I DO NOT WANT THIS. Any station with internet will surf or share
stupid youtube videos before they operate. Internet is not wanted on our
network. We are supposed to be off infrastructure. Anyway, this has caused
him a lot of trouble because he wasn't done with adding and debugging sql
or the time issue. (I debugged his sql to make it work and I reverted back
to a previous time class that I tweaked) Not sure why he went to sql either
but it is working now. But I noticed he has a separate tk form for the
opening sequence now.. Maybe he saw our enhancement.. anyway, we can grab
it to modify it for a gui setup. I want to play with his fdlog some more to
see if he has new ideas we might actually like. Especially if they work. I
haven't seen his version in a while. I used to care that his program and
mine could work together but not anymore.

I love the modular idea! That would be so cool! I thought the program would
interface digital programs like fldigi or transmit/decode morse. But other
contests would be great!

About the setup, my notes this year included finding a better setup. Maybe
putting a txt file named Master in the files. After the setup, the file is
renamed CLIENT. Maybe FDLog Enhanced has the zip file with the CLIENT txt
file ready to share with others so it knows not to ask for setup. Or maybe
create a setup program that creates the zip (with his custom name) to share
the program for the other nodes so it will not ask to setup. It's an idea.
Maybe part of the modular idea..

Imagine this: A "Scoreboard" node that can be identified by the txt file
above renamed "SCOREBOARD". It sits on the info table. Maybe it has a map
of the states contacted. It could give a description of Amateur Radio. A
description of the contest. A scoreboard of the operators and how many
contacts, their current points, the groups stats, a lot of stats like: how
many visitors, countdown of how much time left in the contest etc. The page
can change like a scoreboard.  It would be a nice backup for single
operation (I was 1D this year since I moved). Anyway, I've wanted this
scoreboard for years now.

I got the vision, just not the talent. :)

The program is a lot of fun, thank you so much for helping.

73

Scott Hibbs
812-581-0631

**Comment by nouse4anick** [comment]
So one of the forks that I saw (i have a fork and we7u has a fork) has had the copyright updated, it acknowledges your fork (not mine, I consider mine a 'development' phase fork anyways). and has left a few things in the main python file.

so I'll deal with some of your points in bullet form:

- I looked at the original fdlog site, the last update is from 2017, my original fork is 2 versions removed. I do not think we need to load any changes from the original but I'll look at it.

- python 3: I don't think we need to move to it... yet.... so far the main differences from one site is the division op, print function, unicode, xrange, error handling and the _future_ module. I think we can hold off porting to 3 until we undergo the major overhaul I'm thinking of

- internet networking: we don't need this. its a stupid idea and not what this is meant for. the ONLY reason I can see for something like this is if they use individual hotspots attached to their computers for their network. I say leave it out and keep local networking

- I'll look at how they did the gui, I was also thinking about making a cli version that ran as only a server in the background (ie headless pi), that everyone talked to and would act as a time server and share the log.

- I'll look into seeing if i can get it to interface with fldigi, that would make logging a bit easier on everyone

- setup: I bet we could ping the network and see if there is already a server on the network that is configured. I do not like the idea of passing files around on field day especially if new equipment needs to be brought up.

- as for the scoreboard there are a couple of options we can do, one is the program can host a webpage that you can point a browser to and have it update every 10 minutes.

- also for the sql are you talking about him changing from sqlite?

hope you're enjoying your 4th, I'm about to go see the fireworks!

Art

**Comment by nouse4anick** [comment]
i just ran the program, I like the gui popup for the setup, I think we can adapt that.

I don't see a wide spread use for the gps time. HOWEVER it might be something to consider for the users of the DRAWS board (http://nwdigitalradio.com/) which has gps built into it as well as a rtc, however the current version has the software that pulls gps time and updates the system clock to that time.

aside from that I am not seeing much off the top of my head that we could adapt that we don't already have something better in place in this version that we've been working on.

**Comment by scotthibbs** [comment]
Nick, 

I agree with everything you stated. 

I think our Time Class is just fine. Working on this more will just keep us from doing better things. 

Not sure about the cli, but the scoreboard could be used headless if one doesn't want to see the webpage. It could be time master, serve as a non-station backup etc. 

Did you notice Alan's file "miniweb.py"? This is how Alan distributes the program to the other computers on the network. Maybe we can use it somehow..

My suggestion was the program files shared with the nodes. The admin runs FDLog Enhanced and sets up the contest. The program creates a "client" txt file with that info. That file is included for the copies shared with the nodes. Program runs, sees the client file and skips setup. 

And yes about sql. The program ran fine without it. Not sure why sql was necessary. I was just ranting. 

The other forks are very active so far. Did you see lgadalla-impinj's work on techn0mad's fork? He's taking all the classes out of the main program. This maybe the start of your modular idea..

Maybe at some point we join them.. Would love to talk to them. 

Enjoy the 4th!!

**Pull request merged**
